apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: goapp-pod
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: HELLO_ARGOCD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecret.name }}
                  key: {{ .Values.envSecret.key }}
---
